x = int(input())

print ("1 x {} = {}". format(x, x*1))
print ("2 x {} = {}". format(x, x*2))
print ("3 x {} = {}". format(x, x*3))
print ("4 x {} = {}". format(x, x*4))
print ("5 x {} = {}". format(x, x*5))
print ("6 x {} = {}". format(x, x*6))
print ("7 x {} = {}". format(x, x*7))
print ("8 x {} = {}". format(x, x*8))
print ("9 x {} = {}". format(x, x*9))
print ("10 x {} = {}". format(x, x*10))
